name: run-blazemeter-test-actions-workflow
env:
  apikey: '673e0985b554e480881605e1'
  apisecret: '570f3adadb95ce61bccb6a1097e9f0c69fa5e1d650b5040ea74aeaaa1f0d63bc5babbf0b'
  testid: '9874872'
  modeldata: '{"email": "\"asas@gmail.com/\"","password": "\"asas/\""}'
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:    
      - name: Run Blazemeter test
        #uses: ./ # Uses an action in the root directory
        uses:  dnyanehblazerunner/BlazeAction@v5
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          testid: ${{env.testid}}
          modeldata: ${{ toJSON(env.modeldata) }} 
         
