name: run-blazemeter-test-actions-workflow
env:
  apikey: 'bc3fe837c92453778f625575'
  apisecret: '035b3c858209d84b04ee9946cabd120efe3b18ea4767c39147976b5ef1b598782c97d0c2'
  testid: '9927679'
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:    
      - name: Run Blazemeter test
        #uses: ./ # Uses an action in the root directory
        uses: PoojaMutadak504/DockerAction@v8
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          testid: ${{env.testid}}
          supportedfolderPath: './Supporting Files'
