name: run-blazemeter-test-actions-workflow
env:
  apikey: 'b9107809a101b8b788e9964f'
  apisecret: '24da75ad1302cfb986fe84846288e3c9aecb61742a269f0927db60b286aedbf4f9c28df6'
  testid: '9092315'
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:    
      - name: Run Blazemeter test
        #uses: ./ # Uses an action in the root directory
        uses: PoojaMutadak504/DockerAction@v4
        id: run-test
        with:
          apikey: ${{env.apikey}}
          apisecret: ${{env.apisecret}}
          testid: ${{env.testid}}
          supportedfolderPath: ./Supporting Files
