name: run-blazemeter-test-actions-workflow
env:
  apikey: 'b9107809a101b8b788e9964f'
  apisecret: '24da75ad1302cfb986fe84846288e3c9aecb61742a269f0927db60b286aedbf4f9c28df6'
  testid: '9092315'
on: push
jobs:
  run-existing-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: nguyenvanuyn96/str-find-and-replace-action@master
        with:
          find: "{{imageName}}"
          replace: "blazerunner/abc"
          include: "docker-compose.yml" # Will match all README.md files in any nested directory
      - name: Run existing Test
        run: docker-compose run -e apikey=${{env.apikey}} -e apisecret=${{env.apisecret}} -e testid=${{env.testid}} blazemeter
     
