name: run-blazemeter-test-actions-workflow
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run existing Test
        run: docker-compose run -e apikey=b9107809a101b8b788e9964f -e apisecret=24da75ad1302cfb986fe84846288e3c9aecb61742a269f0927db60b286aedbf4f9c28df6 -e testid=9092315 blazemeter
     
